apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: frontend
    labels: 
      name: frontend
  spec:
    replicas: 1
    selector:
      name: frontend
    template:
     metadata:
      labels:
        name: frontend
     spec:
       containers:
       - name: frontend
         image: katacoda/docker-http-server:health
         livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 1
           periodSeconds: 1
         readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 1
           periodSeconds: 1
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: bad-frontend
    labels: 
      name: bad-frontend
  spec:
    replicas: 1
    selector:
      name: bad-frontend
    template:
     metadata:
      labels:
        name: bad-frontend
     spec:
       containers:
       - name: bad-frontend
         image: katacoda/docker-http-server:unhealthy
         livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 1
           periodSeconds: 1
         readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 1
           periodSeconds: 1
- apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels: 
      name: frontend
      kubernetes.io/cluster-service: "true"        
  spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 30080
    selector:
      name: frontend  
